use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 3.0'
pod 'RNCryptor', '~> 4.0.0-beta'

xcodeproj 'kpm.xcodeproj'

link_with 'kpm', 'kpmTests'

target 'kpm' do

end

target 'kpmTests' do

end

